export const textes = {
  fr: {
    changerLangue: "Passer en anglais",
    navigation: {
      seConnecter: "Se connecter",
      sEnregistrer: "S’enregistrer",
    },
    slogan: "Every goal start with plan.",
    objectifs: [
      "Définissez vos objectifs",
      "Organisez vos tâches",
      "Suivez votre progression",
      "Planifiez votre temps",
      "Partagez et rejoignez des objectifs",
    ],
    stats: [
      { valeur: "2 265", libelle: "Participants actifs" },
      { valeur: "87 %", libelle: "Taux de réussite moyen" },
      { valeur: "47", libelle: "Objectifs disponibles" },
      { valeur: "21 j", libelle: "Série la plus longue" },
    ],
    cta: {
      titre: "Rejoignez LifeMap et commencez à atteindre vos objectifs dès aujourd’hui.",
      bouton: "Créer un compte",
    },
    explorer: {
      titre: "Explorer",
      recherche: "Rechercher un objectif…",
      votes: "Votes",
      nom: "Nom",
      description: "Description",
      termine: "Terminé",
      type: "Type",
      progression: "Progression",
      participants: "Participants",
      participer: "Participer",
      quitter: "Quitter",
      fois: "fois",
      completes: "complétés",
      aucun: "Aucun objectif communautaire pour l’instant.",
      aucunResultat: "Aucun objectif ne correspond à ta recherche.",
      proposer: "Proposer un objectif",
      annuler: "Annuler",
      creer: "Créer",
      nomPlaceholder: "Nom de l’objectif",
      descriptionPlaceholder: "Description (optionnelle)",
      listeRejoints: "Objectifs rejoints",
      tousTermine: "Tous les participants ont terminé !",
      uniteSerie: {
        quotidien: "jours d’affilée",
        hebdomadaire: "semaines d’affilée",
        mensuel: "mois d’affilée",
        unique: "",
      },
    },
    agenda: {
      titre: "Agenda",
      moisPrecedent: "Mois précédent",
      moisSuivant: "Mois suivant",
      aujourdhui: "Aujourd’hui",
      aucunCeJour: "Aucun événement ce jour.",
      ajouter: "Ajouter",
      titrePlaceholder: "Titre de l’événement",
      debut: "Début",
      fin: "Fin",
      jourFin: "Dernier jour (optionnel)",
      touteLaJournee: "Toute la journée",
      supprimer: "Supprimer",
      legendeActif: "Objectifs validés",
      evenements: { one: "événement", other: "événements" },
      joursActifs: { one: "jour actif", other: "jours actifs" },
    },
    profil: {
      titre: "Profil",
      chargement: "Chargement…",
      deconnexion: "Se déconnecter",
      changerPhoto: "Changer la photo",
      photoTropLourde: "Image trop lourde (2 Mo maximum).",
      photoInvalide: "Choisis un fichier image.",
      envoiEnCours: "Envoi…",
      membreDepuis: "Membre depuis",
      validations: "Validations",
      meilleureSerie: "Meilleure série",
      objectifsActifs: "Objectifs actifs",
      statistiques: "Statistiques",
      activite: {
        titre: "Activité récente",
        vide: "Aucune activité pour l’instant.",
        cree: "Créé",
        valide: "Validé",
      },
      archive: {
        titre: "Archive",
        vide: "Aucun objectif archivé.",
        restaurer: "Restaurer",
        supprimer: "Supprimer",
        confirmer: "Confirmer ?",
        versListe: "Restaurer vers la liste",
        avertissement: "La suppression définitive efface aussi l’historique de validations.",
      },
      rgpd: {
        titre: "Mes données (RGPD)",
        texte:
          "LifeMap ne stocke que ce que tu crées : ton profil (pseudo, email, photo), tes objectifs, listes, validations et événements. Ces données ne sont jamais partagées avec des tiers. Tu peux les modifier ici (pseudo, photo), les exporter ci-dessous, ou tout supprimer depuis les Paramètres.",
        exporter: "Télécharger mes données",
      },
    },
    parametres: {
      titre: "Paramètres",
      langue: "Langue",
      motDePasse: "Mot de passe",
      motDePasseBouton: "Mettre à jour",
      motDePasseSucces: "Mot de passe mis à jour.",
      compte: "Compte & confidentialité",
      supprimerAvertissement:
        "La suppression du compte efface définitivement toutes tes données (objectifs, listes, historique). Cette action est irréversible.",
      supprimerCompte: "Supprimer mon compte",
      supprimerConfirmer: "Confirmer la suppression ?",
    },
    dashboard: {
      lifeMapNav: "Life Map",
      agenda: "Agenda",
      explorer: "Explorer",
      bonjour: "Bonjour",
      sousTitre: "Concentre-toi sur l’essentiel.",
      objectifJournalier: "Objectif journalier",
      faits: { one: "fait", other: "faits" },
      restants: { one: "restant", other: "restants" },
      tresBien: "Très bien, continue !",
      objectifsTermines: "Objectifs terminés",
      total: "Au total",
      prochainEvenement: "Prochain événement",
      aucunEvenement: "Aucun événement à venir",
      categories: {
        quotidien: "Quotidien",
        hebdomadaire: "Hebdomadaire",
        mensuel: "Mensuel",
        unique: "Unique",
        sansType: "Sans type",
      },
      aFaire: "À faire aujourd’hui",
      toutFait: "Tout est fait pour aujourd’hui 🎉",
      aucunObjectif: "Aucun objectif pour l’instant.",
      lifeMap: "Votre Life Map",
      ajouterListe: "Ajouter une liste",
      ajouterItem: "Ajouter un item",
      nomListe: "Nom de la liste",
      nomItem: "Nom de l’objectif",
      typeObjectif: "Type",
      erreurAjoutObjectif: "Impossible d’ajouter l’objectif :",
      supprimerListe: "Supprimer la liste",
      deplacerListe: "Glisser pour déplacer la liste",
      deplacerCarte: "Glisser pour déplacer la carte",
      archiverItem: "Archiver",
      renommer: "Renommer",
      voirPlus: "Voir plus",
      voirMoins: "Voir moins",
      objectifRejoint: "Objectif rejoint",
    },
    assistantIa: {
      bouton: "Définir mes objectifs avec l’IA",
      titre: "Décomposer un objectif",
      intro:
        "Décris un objectif large : l’IA propose des sous-objectifs concrets à ajouter à ta Life Map.",
      placeholder: "Ex. Apprendre l’espagnol, Me remettre en forme…",
      listeCible: "Liste cible",
      nouvelleListe: "Nouvelle liste…",
      nomNouvelleListePlaceholder: "Nom de la nouvelle liste",
      generer: "Générer",
      resultatsIntro: "Sélectionne les sous-objectifs à ajouter :",
      ajouter: "Ajouter à la Life Map",
      annuler: "Annuler",
      erreur: "L’assistant n’a pas pu générer de suggestions. Réessaie.",
    },
    choixPseudo: {
      titre: "Choisis un pseudo",
      intro: "Comment veux-tu apparaître dans LifeMap ?",
      placeholder: "Ton pseudo",
      bouton: "Continuer",
    },
    auth: {
      ou: "ou",
      continuerAvec: "Continuer avec",
      email: "Email",
      emailPlaceholder: "vous@exemple.fr",
      motDePasse: "Mot de passe",
      motDePassePlaceholder: "••••••••",
      chargement: "Un instant…",
      erreurIdentifiants: "Email ou mot de passe incorrect.",
      erreurDejaInscrit: "Un compte existe déjà avec cet email.",
      erreurGenerique: "Une erreur est survenue. Réessaie.",
    },
    connexion: {
      titre: "Connexion",
      bouton: "Se connecter",
      pasDeCompte: "Pas encore de compte ?",
      lienInscription: "S’enregistrer",
      motDePasseOublie: "Mot de passe oublié ?",
    },
    oubli: {
      titre: "Mot de passe oublié",
      intro: "Indique ton email : tu recevras un lien pour choisir un nouveau mot de passe.",
      bouton: "Envoyer le lien",
      envoye:
        "Si un compte existe avec cet email, un lien vient d’être envoyé. Pense à regarder tes indésirables.",
      retour: "Retour à la connexion",
    },
    nouveauMotDePasse: {
      titre: "Nouveau mot de passe",
      champ: "Nouveau mot de passe",
      bouton: "Enregistrer",
      lienInvalide: "Ce lien est invalide ou a expiré. Demande-en un nouveau.",
      demanderLien: "Demander un nouveau lien",
      succes: "Mot de passe mis à jour.",
    },
    inscription: {
      titre: "Créer un compte",
      pseudo: "Nom d’utilisateur",
      pseudoPlaceholder: "Votre pseudo",
      bouton: "Créer un compte",
      dejaCompte: "Déjà un compte ?",
      lienConnexion: "Se connecter",
      succesConfirmation: "Compte créé ! Vérifie ta boîte mail pour confirmer ton adresse.",
      criteres: [
        "Au moins 8 caractères",
        "Une majuscule",
        "Une minuscule",
        "Un chiffre",
        "Un caractère spécial",
      ],
    },
  },

  en: {
    changerLangue: "Switch to French",
    navigation: {
      seConnecter: "Sign in",
      sEnregistrer: "Sign up",
    },
    slogan: "Every goal start with plan.",
    objectifs: [
      "Set your goals",
      "Organize your tasks",
      "Track your progress",
      "Plan your time",
      "Share and join goals",
    ],
    stats: [
      { valeur: "2,265", libelle: "Active participants" },
      { valeur: "87%", libelle: "Average success rate" },
      { valeur: "47", libelle: "Goals available" },
      { valeur: "21d", libelle: "Longest streak" },
    ],
    cta: {
      titre: "Join LifeMap and start reaching your goals today.",
      bouton: "Create an account",
    },
    explorer: {
      titre: "Explore",
      recherche: "Search for a goal…",
      votes: "Votes",
      nom: "Name",
      description: "Description",
      termine: "Completed",
      type: "Type",
      progression: "Progress",
      participants: "Participants",
      participer: "Join",
      quitter: "Leave",
      fois: "times",
      completes: "completed",
      aucun: "No community goals yet.",
      aucunResultat: "No goal matches your search.",
      proposer: "Suggest a goal",
      annuler: "Cancel",
      creer: "Create",
      nomPlaceholder: "Goal name",
      descriptionPlaceholder: "Description (optional)",
      listeRejoints: "Joined goals",
      tousTermine: "All participants completed it!",
      uniteSerie: {
        quotidien: "days in a row",
        hebdomadaire: "weeks in a row",
        mensuel: "months in a row",
        unique: "",
      },
    },
    agenda: {
      titre: "Agenda",
      moisPrecedent: "Previous month",
      moisSuivant: "Next month",
      aujourdhui: "Today",
      aucunCeJour: "No event on this day.",
      ajouter: "Add",
      titrePlaceholder: "Event title",
      debut: "Start",
      fin: "End",
      jourFin: "Last day (optional)",
      touteLaJournee: "All day",
      supprimer: "Delete",
      legendeActif: "Goals completed",
      evenements: { one: "event", other: "events" },
      joursActifs: { one: "active day", other: "active days" },
    },
    profil: {
      titre: "Profile",
      chargement: "Loading…",
      deconnexion: "Sign out",
      changerPhoto: "Change photo",
      photoTropLourde: "Image too large (2 MB maximum).",
      photoInvalide: "Please choose an image file.",
      envoiEnCours: "Uploading…",
      membreDepuis: "Member since",
      validations: "Completions",
      meilleureSerie: "Best streak",
      objectifsActifs: "Active goals",
      statistiques: "Statistics",
      activite: {
        titre: "Recent activity",
        vide: "No activity yet.",
        cree: "Created",
        valide: "Completed",
      },
      archive: {
        titre: "Archive",
        vide: "No archived goals.",
        restaurer: "Restore",
        supprimer: "Delete",
        confirmer: "Confirm?",
        versListe: "Restore to list",
        avertissement: "Permanent deletion also erases the completion history.",
      },
      rgpd: {
        titre: "My data (GDPR)",
        texte:
          "LifeMap only stores what you create: your profile (username, email, photo), your goals, lists, completions and events. This data is never shared with third parties. You can edit it here (username, photo), export it below, or delete everything from Settings.",
        exporter: "Download my data",
      },
    },
    parametres: {
      titre: "Settings",
      langue: "Language",
      motDePasse: "Password",
      motDePasseBouton: "Update",
      motDePasseSucces: "Password updated.",
      compte: "Account & privacy",
      supprimerAvertissement:
        "Deleting your account permanently erases all your data (goals, lists, history). This action cannot be undone.",
      supprimerCompte: "Delete my account",
      supprimerConfirmer: "Confirm deletion?",
    },
    dashboard: {
      lifeMapNav: "Life Map",
      agenda: "Agenda",
      explorer: "Explore",
      bonjour: "Hello",
      sousTitre: "Focus on what matters.",
      objectifJournalier: "Daily goal",
      faits: { one: "done", other: "done" },
      restants: { one: "left", other: "left" },
      tresBien: "Great, keep going!",
      objectifsTermines: "Completed goals",
      total: "All time",
      prochainEvenement: "Next event",
      aucunEvenement: "No upcoming event",
      categories: {
        quotidien: "Daily",
        hebdomadaire: "Weekly",
        mensuel: "Monthly",
        unique: "One-off",
        sansType: "No type",
      },
      aFaire: "To do today",
      toutFait: "All done for today 🎉",
      aucunObjectif: "No goals yet.",
      lifeMap: "Your Life Map",
      ajouterListe: "Add a list",
      ajouterItem: "Add an item",
      nomListe: "List name",
      nomItem: "Goal name",
      typeObjectif: "Type",
      erreurAjoutObjectif: "Couldn’t add the goal:",
      supprimerListe: "Delete list",
      deplacerListe: "Drag to move the list",
      deplacerCarte: "Drag to move the card",
      archiverItem: "Archive",
      renommer: "Rename",
      voirPlus: "Show more",
      voirMoins: "Show less",
      objectifRejoint: "Joined goal",
    },
    assistantIa: {
      bouton: "Define my goals with AI",
      titre: "Break down a goal",
      intro:
        "Describe a broad goal: the AI suggests concrete sub-goals to add to your Life Map.",
      placeholder: "E.g. Learn Spanish, Get back in shape…",
      listeCible: "Target list",
      nouvelleListe: "New list…",
      nomNouvelleListePlaceholder: "New list name",
      generer: "Generate",
      resultatsIntro: "Select the sub-goals to add:",
      ajouter: "Add to Life Map",
      annuler: "Cancel",
      erreur: "The assistant couldn't generate suggestions. Try again.",
    },
    choixPseudo: {
      titre: "Choose a username",
      intro: "How should we display you in LifeMap?",
      placeholder: "Your username",
      bouton: "Continue",
    },
    auth: {
      ou: "or",
      continuerAvec: "Continue with",
      email: "Email",
      emailPlaceholder: "you@example.com",
      motDePasse: "Password",
      motDePassePlaceholder: "••••••••",
      chargement: "One moment…",
      erreurIdentifiants: "Incorrect email or password.",
      erreurDejaInscrit: "An account already exists with this email.",
      erreurGenerique: "Something went wrong. Please try again.",
    },
    connexion: {
      titre: "Sign in",
      bouton: "Sign in",
      pasDeCompte: "No account yet?",
      lienInscription: "Sign up",
      motDePasseOublie: "Forgot password?",
    },
    oubli: {
      titre: "Forgot password",
      intro: "Enter your email: you'll receive a link to choose a new password.",
      bouton: "Send the link",
      envoye:
        "If an account exists with this email, a link has just been sent. Remember to check your spam folder.",
      retour: "Back to sign in",
    },
    nouveauMotDePasse: {
      titre: "New password",
      champ: "New password",
      bouton: "Save",
      lienInvalide: "This link is invalid or has expired. Please request a new one.",
      demanderLien: "Request a new link",
      succes: "Password updated.",
    },
    inscription: {
      titre: "Create an account",
      pseudo: "Username",
      pseudoPlaceholder: "Your username",
      bouton: "Create an account",
      dejaCompte: "Already have an account?",
      lienConnexion: "Sign in",
      succesConfirmation: "Account created! Check your inbox to confirm your email.",
      criteres: [
        "At least 8 characters",
        "One uppercase letter",
        "One lowercase letter",
        "One digit",
        "One special character",
      ],
    },
  },
};
